select * 
from employee;

select *
from department;

-- Query to list employees data with the following changes:

/*
 The names of all of the employees must be stored with the first letter of each name in uppercase, and the rest of the name in lowercase.
 The e-mail addresses are incorrect.  All of them must be modified to add “@gmail.com” to the string they currently have, but the current value must be changed to lowercase.
 Phone numbers have dots, but we want them replaced by hyphens.
 We need a new column called “CODE” which will be generated by extracting the part of the name that appears before the first blank space, and then removing all vowels from it, so, for an employee called ‘CARLOS’ the code would be ‘CRLS’. 
 */

select id,
  initcap(name) as name,
  birthdate,
  replace(phone,'.','-') as phone,
  salary,
  department_id,
  hire_date,
  job_id,
  lower(email) || '@gmail.com' as email,
  translate(substr(name,1,instr(name,' ')-1),'*AEIOU','*') as code
from employee;

--Write a query to generate a list of employees following these requirements:
/*
We don’t need the complete phone number. In this report, we only want the numbers that are between the first and second dots, for example, for a number like this 515.123.4567 the report must display ‘123’ only.
Please don’t include employees hired before 2010.
The report must be ordered by salary, in descending order. 
*/

select  id,
  name,
  birthdate,
  phone,
  substr(phone, instr(phone, '.')+1, to_number(instr(phone,'.',1,2) - instr(phone,'.')-1)) as phone,
  salary,
  department_Id,
  hire_date,
  job_id,
  email
from Employee
where hire_date >= to_date('01-01-2010', 'dd-mm-yyyy')
order by salary desc;

-- Write the query needed to generate a report with the following characteristics. For this task assume that a month has 30 days:
/*
The report must include the names, job_id, salary, daily salary, and the result of applying the round, trunc, ceil and floor functions to the daily salary calculation.
The report must include only employees whose daily salary is an integer and either were hired after 2010 or work for the ‘IT’ department.
*/

select name, 
       job_id, 
       salary, 
       (salary/30) as daily_salary,
       round(salary/30),
       trunc(salary/30),
       ceil(salary/30),
       floor(salary/30) 
from employee e
where hire_date >= to_date('01-01-2010', 'dd-mm-yyyy')
and MOD((salary/30),1) = 0
or department_id = 3;


-- Oracle Live Session change date format.

alter session set NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

--Write the query necessary to generate the report with the following characteristics:

/* 
The report must include the employee id, name, and hire date.

It must include a column that tells us for how many months the employee has worked for the company.

Every employee receives a raise after 6 months of working for the company. Include a column that tells us the date in which they earned the right for the mentioned raise.

Every employee is sent to a short induction the next Monday after they are hired. Include a column that tells us the date in which they attended their induction.

Every employee is subscribed to the company’s monthly newsletter on the first day of the next month after they are hired. Add a column that tells us the date in which they were subscribed to the newsletter.

Do not include employees from the IT department.
*/

select
    id,
    name,
    hire_date,
    trunc(months_between(sysdate, hire_date)) as months_worked,
    add_months(hire_date, 6) as raise_earned_date,
    next_day(hire_date, 'monday') as induction_date,
    last_day(hire_date)+1 as newsletter_day
from employee
where department_id != 3;

/*Generate a report of all of the employees who were born after 1970 and for whom we have a phone number registered. In the report, the department_id must be displayed using 4 digits, left-padded with zeros. The salary must be displayed with your local currency symbol and 2 decimals and with commas as the thousands separator.

Please add an additional column called “ALT_BIRTHDATE” that will result from swapping the month and day parts of the birthdate, so, for example, if the birthdate is 10-Mar-2015, the alternate birthdate would be 03-Oct-2015 (the day becomes the month and the month becomes the day). If the resulting date is invalid, this column should return NULL. */

select name,birthdate,phone,
  to_char(department_id,'fm0000') as department_id,
  to_char(salary,'fmL99,990.00') as salary,
  to_date(to_char(birthdate,'ddmmyyyy') default null on conversion error,'mmddyyyy') as alt_birthdate
from employee e
where trunc(birthdate, 'yy') >= to_date(1970, 'yyyy')
--where birthdate > to_date('31-12-1969', 'dd-mm-yyyy')
and phone is not null;


/* Generate a second report that includes all of the employees that were hired before 2015 and earn more than 2500 or were hired in 2015 but earn less than 3000. The report must include the employees’ names, the day and month of the birthdate, and only the month (name of the month) and year of the hire date.

The company is planning to give every employee a surprise bonus for the amount of the last 4 digits of their phone number, so please include an additional column that displays the amount of this bonus for every employee. This amount must be displayed with your local currency symbol and 2 decimals.

They will receive this surprise bonus in the month that corresponds to the last digit of their phone number, so, for example, if the employee’s phone number ends with a 4, it means that he must receive his bonus in April. Please include an additional column that tells us the name of the month in which they must receive their bonus. If any employee has a phone number that ends in a number that is not a valid month, they must receive their bonus in December. */

select 
    name,
    to_char(birthdate,'dd/mm') as birthdate,
    to_char(hire_date,'fmMonth yyyy') as hire_date,
    to_char(to_number(substr(phone,-4)),'L9990.00') as bonus,
    to_char(to_date(substr(phone,-1) default '12' on conversion error,'mm'),'Month') as bonus_month
from employee
where trunc(hire_date, 'yyyy') < to_date('01-01-2015', 'dd-mm-yyyy') and salary > 2500
or trunc(hire_date, 'yyyy') = to_date('01-01-2015', 'dd-mm-yyyy') and salary < 3000;

/*The company wants to give a rise to all employees according to these conditions:

- Employees who work in the ACCOUNTING department get a 10% increase to their salary.

- Employees who work in the MARKETING department get a 15% increase to their salary.

- Employees from the other departments get a 20% increase to their salary.

Please generate a report that includes the employee id, name, current salary, and new salary. 
Please generate 2 columns for the new salary. To calculate the first one use the DECODE function and for the second one use a simple CASE expression. 
The result in both new salary columns must be the same.
 */

 select
    id,
    name,
    salary as current_salary,
    salary + (salary * decode(department_id,1,0.10,2,0.15,0.20)) as new_salary_1,
    salary + (salary * 
    case 
        when department_id = 1
            then 0.1
        when department_id = 2
            then 2
        else 3
    end) as new_salary_2
from employee;

/*
The company is planning to assign a classification to each employee based on the salary they earn. The classification would be as follows:

- Employees who earn less than 2500 will be classified as “A”.

- Employees who earn 2500 or more but less than 4000 will be classified as “B”.

- Employees who earn 4000 or more will be classified as “C” if they were hired before 2014 and will be classified as “D” if they were hired in 2014 or 2015.

Please generate a report that includes the employee id, name, salary, the year they were hired, and the classification of each employee, 
but don’t include employees from the MARKETING department, and also don’t include employees who don’t have a phone number registered. 
The report must be ordered by salary and hire_date.
*/

select
    id,
    name,
    salary,
    extract(year from hire_date) as hire_year,
    case
        when salary < 2500
            then 'A'
        when salary >= 2500 and salary < 4000
            then 'B'
        when salary >= 4000 and extract(year from hire_date) < 2014
            then 'C'
        when salary >= 4000 and extract(year from hire_date) >= 2014 and extract(year from hire_date) <= 2015
            then 'D'
        else 'not categorized'
    end as classification
from employee
where department_id != 2
  and phone is not null
order by salary,hire_date;