select * 
from employee;

select *
from department;

-- Query to list employees data with the following changes:

/*
 The names of all of the employees must be stored with the first letter of each name in uppercase, and the rest of the name in lowercase.
 The e-mail addresses are incorrect.  All of them must be modified to add “@gmail.com” to the string they currently have, but the current value must be changed to lowercase.
 Phone numbers have dots, but we want them replaced by hyphens.
 We need a new column called “CODE” which will be generated by extracting the part of the name that appears before the first blank space, and then removing all vowels from it, so, for an employee called ‘CARLOS’ the code would be ‘CRLS’. 
 */

select id,
  initcap(name) as name,
  birthdate,
  replace(phone,'.','-') as phone,
  salary,
  department_id,
  hire_date,
  job_id,
  lower(email) || '@gmail.com' as email,
  translate(substr(name,1,instr(name,' ')-1),'*AEIOU','*') as code
from employee;

--Write a query to generate a list of employees following these requirements:
/*
We don’t need the complete phone number. In this report, we only want the numbers that are between the first and second dots, for example, for a number like this 515.123.4567 the report must display ‘123’ only.
Please don’t include employees hired before 2010.
The report must be ordered by salary, in descending order. 
*/

select  id,
  name,
  birthdate,
  phone,
  substr(phone, instr(phone, '.')+1, to_number(instr(phone,'.',1,2) - instr(phone,'.')-1)) as phone,
  salary,
  department_Id,
  hire_date,
  job_id,
  email
from Employee
where hire_date >= to_date('01-01-2010', 'dd-mm-yyyy')
order by salary desc;

-- Write the query needed to generate a report with the following characteristics. For this task assume that a month has 30 days:
/*
The report must include the names, job_id, salary, daily salary, and the result of applying the round, trunc, ceil and floor functions to the daily salary calculation.
The report must include only employees whose daily salary is an integer and either were hired after 2010 or work for the ‘IT’ department.
*/

select name, 
       job_id, 
       salary, 
       (salary/30) as daily_salary,
       round(salary/30),
       trunc(salary/30),
       ceil(salary/30),
       floor(salary/30) 
from employee e
where hire_date >= to_date('01-01-2010', 'dd-mm-yyyy')
and MOD((salary/30),1) = 0
or department_id = 3;


-- Oracle Live Session change date format.

alter session set NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

--